# Generated by Django 4.2.17 on 2025-01-03 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0003_increase_code_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='question_completion_time',
            field=models.DurationField(blank=True, default=None, null=True, verbose_name='estimated time to complete question'),
        ),
    ]
