version: "3.7"

services:
  db:
    container_name: postgis
    image: postgis/postgis:17-3.5
    env_file: .env
    volumes:
      - postgis-data:/var/lib/postgresql/data
    networks:
      - external-services

  redis:
    container_name: redis
    image: redis:6.2-alpine
    env_file: .env
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis-data:/data
    networks:
      - external-services

networks:
  external-services:
    external: true

volumes:
  postgis-data:
    name: postgis-data
  redis-data:
    name: redis-data
