name: Lint python application

on:
  pull_request:
  push:
    branches:
      - develop

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.5.15"

      - name: Setup cache
        uses: actions/cache@v4
        with:
          path: .venv
          key: uv-venv-${{ hashFiles('uv.lock') }}

      - name: Install dependencies
        run: |
          uv sync

      - name: Lint python projects
        run: |
          uv run ruff format . --check
          uv run ruff check .
        